# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 13:21
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaires', '0002_alter_questionnaire_name_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XFormSubmission',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('json_submission', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='questionnaires.Questionnaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
