# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-31 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0002_auto_20160712_1513'),
        ('party', '0002_remove_all_types_from_tenure_relationship_type'),
        ('xforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xformsubmission',
            name='instanceID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='xformsubmission',
            name='parties',
            field=models.ManyToManyField(related_name='xform_submissions', to='party.Party'),
        ),
        migrations.AddField(
            model_name='xformsubmission',
            name='spatial_units',
            field=models.ManyToManyField(related_name='xform_submissions', to='spatial.SpatialUnit'),
        ),
        migrations.AddField(
            model_name='xformsubmission',
            name='tenure_relationships',
            field=models.ManyToManyField(related_name='xform_submissions', to='party.TenureRelationship'),
        ),
    ]
