# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 18:13
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('xforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xformsubmission',
            name='instanceID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='xformsubmission',
            name='parties',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2500), default=[], size=None),
        ),
        migrations.AddField(
            model_name='xformsubmission',
            name='spatial_units',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2500), default=[], size=None),
        ),
        migrations.AddField(
            model_name='xformsubmission',
            name='tenures',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2500), default=[], size=None),
        ),
    ]
