- name: Provision EC2 instance
  hosts: all
  remote_user: ubuntu
  gather_facts: true
  vars:
    django_settings: config.settings.production
    app_user: cadasta
  vars_files:
    - shared_vars.yml
  roles:
    - deployment/init
    - system/aws
    - system/common
    - db/common
    - db/production
    - cadasta/common
    - cadasta/install
    - cadasta/application
    - cadasta/production
    - webserver/production
    - deployment/wrap
