- hosts: all
  vars:
    django_settings: config.settings.dev
    identifier: local
    app_user: vagrant
  vars_files:
    - shared_vars.yml
  roles:
    - system/common
    - db/common
    - db/development
    - node
    - cadasta/common
    - cadasta/application
    - cadasta/development
    - testing
    - data
