- hosts: all
  vars:
    application_path: /vagrant/
    virtualenv_path: /opt/cadasta/env/
    django_settings: config.settings.dev
    app_user: vagrant
    uwsgi_socket: /tmp/uwsgi.sock
    identifier: local
  vars_files:
    - shared_vars.yml
  roles:
    - system/common
    - db/common
    - db/development
    - node
    - cadasta/application
    - cadasta/development
    - testing
    - data
