#!/bin/bash

# If this is not a Travis build, just execute runtests.py
if [[ -z $TRAVIS ]]
then
  ./runtests.py --functional

# We are on a Travis build
else

  # Perform any final installations and setups before running tests on Travis
  cd cadasta/core
  npm install bootstrap-sass
  cd ..
  ./manage.py migrate
  ./manage.py loadstatic
  ./manage.py loadfunctestfixtures
  ./manage.py runserver 0.0.0.0:8000 &
  until curl http://0:8000 -f; do sleep .1; done  # Wait for the Django server to start up
  cd ..

  export CADASTA_TEST_WEBDRIVER=Firefox
  ./runtests.py --functional -m debug
  ret=$?

  # Kill the Django server
  killall python

  exit $ret
fi
