- name: Configure worker table priviliges
  become: yes
  become_user: postgres
  postgresql_privs: role="worker"
                    privs="SELECT,INSERT,UPDATE"
                    objs="celery_taskmeta,celery_tasksetmeta"
                    db="cadasta"
  listen: migrations called

- name: Configure worker sequence priviliges
  become: yes
  become_user: postgres
  postgresql_privs: role="worker"
                    priv="USAGE"
                    objs="task_id_sequence,taskset_id_sequence"
                    type="sequence"
                    db="cadasta"
  listen:
    - migrations called
