# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 10:23
from __future__ import unicode_literals

import buckets.fields
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import resources.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentObject',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('object_id', models.CharField(blank=True, max_length=24, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', buckets.fields.S3FileField(upload_to='resources', validators=[resources.validators.validate_file_type])),
                ('original_file', models.CharField(max_length=200)),
                ('file_versions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('mime_type', models.CharField(max_length=50)),
                ('archived', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contentobject',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_objects', to='resources.Resource'),
        ),
    ]
