# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 12:59
from __future__ import unicode_literals

import buckets.fields
from django.db import migrations, models
import resources.validators


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalresource',
            name='file',
            field=buckets.fields.S3FileField(upload_to='resources'),
        ),
        migrations.AlterField(
            model_name='historicalresource',
            name='mime_type',
            field=models.CharField(max_length=100, validators=[resources.validators.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=buckets.fields.S3FileField(upload_to='resources'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='mime_type',
            field=models.CharField(max_length=100, validators=[resources.validators.validate_file_type]),
        ),
    ]
