# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_add_history_change_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcontentobject',
            name='history_change_reason',
        ),
        migrations.RemoveField(
            model_name='historicalresource',
            name='history_change_reason',
        ),
    ]
