# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 20:15
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialUnit',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ('type', models.CharField(choices=[('PA', 'Parcel'), ('CB', 'Community boundary'), ('BU', 'Building'), ('AP', 'Apartment'), ('PX', 'Project extent'), ('RW', 'Right-of-way'), ('UC', 'Utility corridor'), ('NP', 'National park boundary'), ('MI', 'Miscellaneous')], default='PA', max_length=2)),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpatialUnitRelationship',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('C', 'is-contained-in'), ('S', 'is-split-of'), ('M', 'is-merge-of')], max_length=1)),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Project')),
                ('su1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spatial_unit_one', to='spatial.SpatialUnit')),
                ('su2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spatial_unit_two', to='spatial.SpatialUnit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='spatialunit',
            name='relationships',
            field=models.ManyToManyField(through='spatial.SpatialUnitRelationship', to='spatial.SpatialUnit'),
        ),
    ]
