# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 15:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialunit',
            name='name',
            field=models.CharField(default='Ugh', max_length=200),
        ),
        migrations.AlterField(
            model_name='spatialunit',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='spatialunitrelationship',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
