# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalspatialrelationship',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical spatial relationship'},
        ),
    ]
