# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0002_auto_20160505_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatialunit',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='spatialunit',
            name='relationships',
            field=models.ManyToManyField(related_name='relationship', through='spatial.SpatialUnitRelationship', to='spatial.SpatialUnit'),
        ),
    ]
