# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0002_auto_20160712_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalspatialunit',
            name='type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='spatialunit',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
