# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 16:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0002_auto_20160712_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspatialunit',
            name='geometry_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='spatialunit',
            name='geometry_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
