# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 21:21
from __future__ import unicode_literals

from django.db import migrations, models


def calculate_area_field(apps, schema_editor):
    SpatialUnit = apps.get_model('spatial', 'SpatialUnit')
    SpatialUnit.objects.exclude(geometry=None).extra(
        where=["geometrytype(geometry) LIKE 'POLYGON'"]).update(
        area=Area(Transform('geometry', 3857)))


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0003_custom_location_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspatialunit',
            name='area',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='spatialunit',
            name='area',
            field=models.FloatField(null=True),
        ),
        migrations.RunPython(
            calculate_area_field,
            reverse_code=migrations.RunPython.noop
        ),
    ]
