# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0005_auto_20160506_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spatialunit',
            old_name='extent',
            new_name='geometry',
        ),
    ]
