# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    TABLE_NAME = 'spatial_spatialunit'
    FUNC_NAME = 'calculate_area'
    TRIGGER_NAME = '{}_trigger'.format(FUNC_NAME)

    dependencies = [
        ('spatial', '0005_recalculate_area'),
    ]

    operations = [
        migrations.RunSQL(
            """
                DROP TRIGGER {trigger} ON {table};
                DROP FUNCTION {func}();
            """.format(func=FUNC_NAME, trigger=TRIGGER_NAME, table=TABLE_NAME),
            reverse_sql="""
            CREATE FUNCTION {func}() RETURNS trigger AS $$
            BEGIN
                IF geometrytype(NEW.geometry) LIKE '%POLYGON'
                THEN
                    NEW.area := (SELECT ST_Area(geography(NEW.geometry)));
                ELSE
                    NEW.area := null;
                END IF;
                RETURN NEW;
            END;
            $$ language plpgsql;

            CREATE TRIGGER {trigger}
                BEFORE INSERT OR UPDATE
                ON {table}
                FOR EACH ROW
                EXECUTE PROCEDURE {func}();
            """.format(func=FUNC_NAME, trigger=TRIGGER_NAME, table=TABLE_NAME)
        )
    ]
