# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0006_auto_20160509_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spatialunit',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='spatialunit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spatial_units', to='organization.Project'),
        ),
    ]
