# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-09 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0009_add_audit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalspatialunit',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='spatialunit',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
