# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 23:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0010_increase_max_length_for_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspatialunit',
            name='label',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='spatialunit',
            name='label',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
