from django.utils.translation import ugettext_lazy as _


FORM_LANGS = {
    'af': _("Afrikaans"),
    'ar': _("Arabic"),
    'az': _("Azerbaijani"),
    'be': _("Belarusian"),
    'bg': _("Bulgarian"),
    'bn': _("Bengali"),
    'br': _("Breton"),
    'bs': _("Bosnian"),
    'ca': _("Catalan"),
    'cs': _("Czech"),
    'cy': _("Welsh"),
    'da': _("Danish"),
    'de': _("German"),
    'el': _("Greek"),
    'en': _("English"),
    'eo': _("Esperanto"),
    'es': _("Spanish"),
    'et': _("Estonian"),
    'eu': _("Basque"),
    'fa': _("Persian (Farsi)"),
    'fi': _("Finnish"),
    'fr': _("French"),
    'fy': _("Western Frisian"),
    'ga': _("Irish"),
    'gd': _("Scottish Gaelic"),
    'gl': _("Galician"),
    'he': _("Hebrew"),
    'hi': _("Hindi"),
    'hr': _("Croatian"),
    'hu': _("Hungarian"),
    'ia': _("Interlingua"),
    'id': _("Indonesian"),
    'io': _("Ido"),
    'is': _("Icelandic"),
    'it': _("Italian"),
    'ja': _("Japanese"),
    'ka': _("Georgian"),
    'kk': _("Kazakh"),
    'km': _("Khmer"),
    'kn': _("Kannada"),
    'ko': _("Korean"),
    'lb': _("Luxembourgish"),
    'lt': _("Lithuanian"),
    'lv': _("Latvian"),
    'mk': _("Macedonian"),
    'ml': _("Malayalam"),
    'mn': _("Mongolian"),
    'mr': _("Marathi"),
    'my': _("Burmese"),
    'nb': _("Norwegian (Bokmål)"),
    'ne': _("Nepali"),
    'nl': _("Dutch"),
    'nn': _("Norwegian (Nynorsk)"),
    'os': _("Ossetian"),
    'pa': _("Eastern Punjabi"),
    'pl': _("Polish"),
    'pt': _("Portuguese"),
    'ro': _("Romanian"),
    'ru': _("Russian"),
    'sk': _("Slovak"),
    'sl': _("Slovene"),
    'sq': _("Albanian"),
    'sr': _("Serbian"),
    'sv': _("Swedish"),
    'sw': _("Swahili"),
    'ta': _("Tamil"),
    'te': _("Telugu"),
    'th': _("Thai"),
    'tr': _("Turkish"),
    'tt': _("Tatar"),
    'uk': _("Ukrainian"),
    'ur': _("Urdu"),
    'vi': _("Vietnamese"),
    'kar': _("S'gaw Karen")
}
