# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 17:30
from __future__ import unicode_literals

import accounts.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.manager.UserManager()),
            ],
        ),
    ]
