# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-14 08:46
from __future__ import unicode_literals

from django.db import migrations


def activate_user(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    EmailAddress = apps.get_model('account', 'EmailAddress')

    inactive_users = User.objects.filter(email_verified=False)
    for user in inactive_users:
        try:
            email = EmailAddress.objects.get(user=user, email=user.email)
            if email.verified:
                user.is_active = True
                user.email_verified = True
                user.save()
        except EmailAddress.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            activate_user,
            reverse_code=migrations.RunPython.noop
        )
    ]
