# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_change_pw'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('id', 'Indonesian'), ('pt', 'Portuguese')], default='en-us', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('id', 'Indonesian'), ('pt', 'Portuguese')], default='en-us', max_length=10),
        ),
    ]
