# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_change_pw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='verify_email_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verify_email_by',
        ),
    ]
