# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 11:43
from __future__ import unicode_literals

import buckets.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_change_pw'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='file',
            field=buckets.fields.S3FileField(default=django.utils.timezone.now, upload_to='users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='file',
            field=buckets.fields.S3FileField(default=django.utils.timezone.now, upload_to='users'),
            preserve_default=False,
        ),
    ]
