# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_change_pw'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='created_date',
            field=models.DateTimeField(blank=True, default='2016-01-01 00:00+00', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='last_updated',
            field=models.DateTimeField(blank=True, default='2016-01-01 00:00+00', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default='2016-01-01 00:00+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
