# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_phone_and_verification_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='email',
            field=models.EmailField(db_index=True, default=None, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='phone',
            field=models.CharField(db_index=True, default=None, max_length=16, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=None, max_length=16, null=True, unique=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='verificationdevice',
            name='unverified_phone',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
