# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-30 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_language_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('id', 'Indonesian'), ('it', 'Italian'), ('pt', 'Portuguese')], default='en-us', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('id', 'Indonesian'), ('it', 'Italian'), ('pt', 'Portuguese')], default='en-us', max_length=10),
        ),
    ]
