# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 11:25
from __future__ import unicode_literals

import accounts.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170316_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='mime_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, validators=[accounts.validators.validate_file_type]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='original_file',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='mime_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, validators=[accounts.validators.validate_file_type]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='original_file',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
