# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-29 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_italian_to_lang_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='measurement',
            field=models.CharField(choices=[('metric', 'Metric'), ('imperial', 'Imperial')], default='metric', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='measurement',
            field=models.CharField(choices=[('metric', 'Metric'), ('imperial', 'Imperial')], default='metric', max_length=20),
        ),
    ]
