# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-08 06:16
from __future__ import unicode_literals

import buckets.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_italian_to_lang_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='avatar',
            field=buckets.fields.S3FileField(blank=True, default='/static/img/avatar_sm.jpg', upload_to='avatars'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=buckets.fields.S3FileField(blank=True, default='/static/img/avatar_sm.jpg', upload_to='avatars'),
        ),
    ]
