# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-27 06:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_verificationdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
