# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 22:28
from __future__ import unicode_literals

import buckets.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170703_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='avatar',
            field=buckets.fields.S3FileField(blank=True, default='/static/img/avatar.jpg', upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=buckets.fields.S3FileField(blank=True, default='/static/img/avatar.jpg', upload_to='avatars'),
        ),
    ]
