# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170317_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='original_file',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='original_file',
        ),
    ]
