# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_avatar_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
