# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 08:34
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models import F


def migrate_change_pw_to_update_profile(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.all().update(update_profile=F('change_pw'))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_phone_and_verification_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='update_profile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='update_profile',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(
            migrate_change_pw_to_update_profile,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='change_pw',
        ),
        migrations.RemoveField(
            model_name='user',
            name='change_pw',
        ),
    ]
