# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_phone_and_verification_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='change_pw',
            new_name='update_profile',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='change_pw',
            new_name='update_profile',
        ),
    ]
