# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 14:43
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import organization.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=[], size=None)),
                ('contacts', django.contrib.postgres.fields.jsonb.JSONField(default={}, validators=[organization.validators.validate_contact])),
                ('logo', models.URLField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationRole',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('admin', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('project_slug', models.SlugField(null=True, unique=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=[], size=None)),
                ('contacts', django.contrib.postgres.fields.jsonb.JSONField(default={}, validators=[organization.validators.validate_contact])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('extent', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
                ('access', models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=15)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organization.Organization')),
            ],
            options={
                'ordering': ('organization', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('PU', 'Project User'), ('DC', 'Data Collector'), ('PM', 'Project Manager')], default='PU', max_length=2)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(through='organization.ProjectRole', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(related_name='organizations', through='organization.OrganizationRole', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='projectrole',
            unique_together=set([('project', 'user')]),
        ),
    ]
