# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 10:57
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import organization.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=[], size=None)),
                ('contacts', django.contrib.postgres.fields.jsonb.JSONField(default={}, validators=[organization.validators.validate_contact])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationRole',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('admin', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(through='organization.OrganizationRole', to=settings.AUTH_USER_MODEL),
        ),
    ]
