# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='access',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=15),
        ),
    ]
