# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_project_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='access',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=15),
        ),
    ]
