# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_add_organizationrole_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='created_date',
            field=models.DateTimeField(blank=True, default='2016-01-01 00:00+00', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalorganizationrole',
            name='created_date',
            field=models.DateTimeField(blank=True, default='2016-01-01 00:00+00', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalorganizationrole',
            name='last_updated',
            field=models.DateTimeField(blank=True, default='2016-01-01 00:00+00', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='created_date',
            field=models.DateTimeField(blank=True, default='2016-01-01 00:00+00', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default='2016-01-01 00:00+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationrole',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default='2016-01-01 00:00+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationrole',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default='2016-01-01 00:00+00'),
            preserve_default=False,
        ),
    ]
