# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 08:14
from __future__ import unicode_literals

from django.db import migrations


def remove_public_user_role(apps, schema_editor):
    ProjectRole = apps.get_model("organization", "ProjectRole")
    ProjectRole.objects.filter(role='Pb').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_add_organizationrole_unique'),
    ]

    operations = [
        migrations.RunPython(
            remove_public_user_role, migrations.RunPython.noop),
    ]
