# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-11 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_remove_Pb_project_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='area',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='area',
            field=models.FloatField(default=0),
        ),
    ]
