# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_add_history_change_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorganization',
            name='history_change_reason',
        ),
        migrations.RemoveField(
            model_name='historicalorganizationrole',
            name='history_change_reason',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='history_change_reason',
        ),
        migrations.RemoveField(
            model_name='historicalprojectrole',
            name='history_change_reason',
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='archived_by_org',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='archived_by_org',
            field=models.BooleanField(default=False),
        ),
    ]
