# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_populate_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationrole',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_roles', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_roles', to='auth.Group'),
        ),
    ]
