# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-17 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_group_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationrole',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_roles', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_roles', to='auth.Group'),
        ),
    ]
