# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-31 07:18
from __future__ import unicode_literals

from django.db import migrations


def remove_all_types(apps, schema_editor):
    TenureRelationship = apps.get_model("party", "TenureRelationship")
    TenureRelationshipType = apps.get_model("party", "TenureRelationshipType")
    if TenureRelationshipType.objects.filter(id='FH').exists():
        freehold = TenureRelationshipType.objects.get(id='FH')
        for tr in TenureRelationship.objects.filter(tenure_type__id='AL'):
            tr.tenure_type = freehold
            tr.save()
        TenureRelationshipType.objects.filter(id='AL').delete()


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remove_all_types, do_nothing),
    ]
