# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 10:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import organization.validators


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='contacts',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, validators=[organization.validators.validate_contact]),
        ),
    ]
