# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-04 10:09
from __future__ import unicode_literals

import datetime
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0001_initial'),
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenureRelationship',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('acquired_how', models.CharField(blank=True, choices=[('CS', 'Contractual/Share Crop'), ('CA', 'Customary Arrangement'), ('GF', 'Gift'), ('HS', 'Homestead'), ('IO', 'Informal Occupant'), ('IN', 'Inheritance'), ('LH', 'Leasehold'), ('PF', 'Purchased Freehold'), ('RN', 'Rental'), ('OT', 'Other')], max_length=2, null=True)),
                ('acquired_date', models.DateField(default=datetime.date.today)),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(null=True, blank=True, srid=4326)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party', to='party.Party')),
                ('spatial_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spatial_unit', to='spatial.SpatialUnit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenureRelationshipType',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='tenurerelationship',
            name='tenure_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenure_type', to='party.TenureRelationshipType'),
        ),
        migrations.AddField(
            model_name='party',
            name='tenure_relationships',
            field=models.ManyToManyField(related_name='tenure_relationships_set', through='party.TenureRelationship', to='spatial.SpatialUnit'),
        ),
    ]
