# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_remove_all_types_from_tenure_relationship_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltenurerelationship',
            name='tenure_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tenurerelationship',
            name='tenure_type',
            field=models.CharField(max_length=10),
        ),
    ]
