# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_convert_tenuretype_to_charfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltenurerelationshiptype',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='TenureRelationshipType',
        ),
        migrations.DeleteModel(
            name='HistoricalTenureRelationshipType',
        ),
    ]
