# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0004_add_history_change_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalparty',
            name='history_change_reason',
        ),
        migrations.RemoveField(
            model_name='historicalpartyrelationship',
            name='history_change_reason',
        ),
        migrations.RemoveField(
            model_name='historicaltenurerelationship',
            name='history_change_reason',
        ),
    ]
