# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-09 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0005_add_audit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltenurerelationship',
            name='tenure_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tenurerelationship',
            name='tenure_type',
            field=models.CharField(max_length=100),
        ),
    ]
