# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-18 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_alter_questionnaire_name_version'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionnaire',
            unique_together=set([('project', 'id_string', 'version')]),
        ),
    ]
