# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-10 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_add_project_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalquestion',
            name='label',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalquestiongroup',
            name='label',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='label',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
