# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0004_auto_20160910_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestionnaire',
            name='original_file',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='original_file',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
