# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0006_add_choice_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestionoption',
            name='index',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='index',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
