# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 13:42
from __future__ import unicode_literals
import itertools

from django.db import migrations


def populate_index_fields(apps, schema_editor):
    Question = apps.get_model('questionnaires', 'Question')

    for question in Question.objects.filter(type__in=['S1', 'SM']):
        for opt, idx in zip(question.options.order_by('index'),
                            itertools.count()):
            opt.index = idx + 1
            opt.save()


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0007_add_question_option_index_field'),
    ]

    operations = [
        migrations.RunPython(
            populate_index_fields,
            reverse_code=migrations.RunPython.noop
        )
    ]
