# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0008_populate_question_option_index_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionoption',
            options={'ordering': ('index',)},
        ),
        migrations.AlterField(
            model_name='historicalquestionoption',
            name='index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='index',
            field=models.IntegerField(),
        ),
    ]
