# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-10 17:13
from __future__ import unicode_literals

from django.db import migrations


def migrate_monolingual_labels(apps, schema_editor):
    QuestionGroup = apps.get_model('questionnaires', 'QuestionGroup')
    for qg in QuestionGroup.objects.all():
        qg.label_xlat = qg.label if qg.label is not None else ""
        qg.save()

    Question = apps.get_model('questionnaires', 'Question')
    for q in Question.objects.all():
        q.label_xlat = q.label if q.label is not None else ""
        q.save()

    QuestionOption = apps.get_model('questionnaires', 'QuestionOption')
    for qo in QuestionOption.objects.all():
        qo.label_xlat = qo.label if qo.label is not None else ""
        qo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0010_add_multilingual_labels'),
    ]

    operations = [
        migrations.RunPython(
            migrate_monolingual_labels,
            reverse_code=migrations.RunPython.noop
        )
    ]
