# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-02 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0013_reprocess_multilingual_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='default',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='hint',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='relevant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalquestiongroup',
            name='question_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='questionnaires.QuestionGroup'),
        ),
        migrations.AddField(
            model_name='historicalquestiongroup',
            name='relevant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalquestiongroup',
            name='type',
            field=models.CharField(default='group', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='default',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='relevant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='question_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='questionnaires.QuestionGroup'),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='relevant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='type',
            field=models.CharField(default='group', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalquestionnaire',
            name='version',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='version',
            field=models.BigIntegerField(),
        ),
    ]
