# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-22 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0014_api_additional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='index',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalquestiongroup',
            name='index',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='index',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='index',
            field=models.IntegerField(null=True),
        ),
    ]
