# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 05:38
from __future__ import unicode_literals

import buckets.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_add_organizationrole_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaires', '0017_populate_additional_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFForm',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('instructions', models.TextField(blank=True, max_length=2500, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('file', buckets.fields.S3FileField(blank=True, null=True, upload_to='pdf-form-logos')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfforms', to='organization.Project')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.Questionnaire')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('index',)},
        ),
        migrations.AlterModelOptions(
            name='questiongroup',
            options={'ordering': ('index',)},
        ),
    ]
