# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0017_populate_additional_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('index',)},
        ),
        migrations.AlterModelOptions(
            name='questiongroup',
            options={'ordering': ('index',)},
        ),
    ]
