# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import questionnaires.validators


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0018_add_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='gps_accuracy',
            field=models.FloatField(blank=True, null=True, validators=[questionnaires.validators.validate_accuracy]),
        ),
        migrations.AddField(
            model_name='question',
            name='gps_accuracy',
            field=models.FloatField(blank=True, null=True, validators=[questionnaires.validators.validate_accuracy]),
        ),
    ]
