# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0018_add_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='created_date',
            field=models.DateTimeField(blank=True, default='2016-01-01 00:00+00', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='last_updated',
            field=models.DateTimeField(blank=True, default='2016-01-01 00:00+00', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalquestiongroup',
            name='created_date',
            field=models.DateTimeField(blank=True, default='2016-01-01 00:00+00', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalquestiongroup',
            name='last_updated',
            field=models.DateTimeField(blank=True, default='2016-01-01 00:00+00', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalquestionnaire',
            name='created_date',
            field=models.DateTimeField(blank=True, default='2016-01-01 00:00+00', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalquestionnaire',
            name='last_updated',
            field=models.DateTimeField(blank=True, default='2016-01-01 00:00+00', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalquestionoption',
            name='created_date',
            field=models.DateTimeField(blank=True, default='2016-01-01 00:00+00', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalquestionoption',
            name='last_updated',
            field=models.DateTimeField(blank=True, default='2016-01-01 00:00+00', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default='2016-01-01 00:00+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default='2016-01-01 00:00+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default='2016-01-01 00:00+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default='2016-01-01 00:00+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionoption',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
