# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0020_add_history_change_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalquestion',
            name='history_change_reason',
        ),
        migrations.RemoveField(
            model_name='historicalquestiongroup',
            name='history_change_reason',
        ),
        migrations.RemoveField(
            model_name='historicalquestionnaire',
            name='history_change_reason',
        ),
        migrations.RemoveField(
            model_name='historicalquestionoption',
            name='history_change_reason',
        ),
    ]
