# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-25 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0021_add_audit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalquestion',
            name='relevant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalquestiongroup',
            name='relevant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='relevant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='relevant',
            field=models.TextField(blank=True, null=True),
        ),
    ]
