# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-10 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0021_add_audit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='appearance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='appearance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
