- name: Write development site configuration to sites-available
  become: yes
  become_user: root
  template: src=nginx-development
            dest="/etc/nginx/sites-available/cadasta-development"
  notify:
    - Restart nginx

- name: Enable development site
  become: yes
  become_user: root
  file: src="/etc/nginx/sites-available/cadasta-development"
        dest="/etc/nginx/sites-enabled/cadasta-development"
        state=link
  notify:
    - Restart nginx
