QUESTION_TYPES = (
    ('IN', 'integer'),
    ('DE', 'decimal'),
    ('TX', 'text'),
    ('S1', 'select one'),
    ('SM', 'select all that apply'),
    ('NO', 'note'),
    ('GP', 'geopoint'),
    ('GT', 'geotrace'),
    ('GS', 'geoshape'),
    ('DA', 'date'),
    ('TI', 'time'),
    ('DT', 'dateTime'),
    ('CA', 'calculate'),
    ('AC', 'acknowledge'),
    ('PH', 'photo'),
    ('AU', 'audio'),
    ('VI', 'video'),
    ('BC', 'barcode'),

    # Meta data
    ('ST', 'start'),
    ('EN', 'end'),
    ('TD', 'today'),
    ('DI', 'deviceid'),
    ('SI', 'subsciberid'),
    ('SS', 'simserial'),
    ('PN', 'phonenumber'))
