#!/usr/bin/env python3

import os.path, sys, re, textwrap
import random, string, uuid
import boto3

import config


if len(sys.argv) != 2:
    print('Usage: list-deployments aws-profile')
    sys.exit(1)

aws_profile = sys.argv[1]

try:
    aws = boto3.session.Session(profile_name=aws_profile)
    config.set_session(aws)
except:
    print('FAILED TO CREATE AWS SESSION USING PROFILE "' + aws_profile + '"')
    sys.exit(1)

for d in sorted(config.list()):
    print(d.replace('.json', ''))
